version: '2.1'
services:

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4567:4567"
    environment:
      - SERVICES=dynamodb
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamodb-admin:
    depends_on:
      - "localstack"
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
