service: finance-service-users

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-dynamodb-local
  - serverless-bundle
  - serverless-pseudo-parameters

# Create an optimized package for our functions
package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  tracing: 
    apiGateway: true
    lambda: true

  environment:
    USERS_TABLE: ${self:provider.stage}-DB-FS-Users

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource:
        - 'Fn::ImportValue': ${self:provider.stage}-DB-FS-UsersArn

functions:
  createUser:
    handler: handlers/create.handler
    events:
      - http:
          path: /users
          method: post
          cors: true
  updateUser: 
    handler: handlers/update.handler
    events:
      - http:
          path: /users/{id}
          method: put
          cors: true
  findUser:
    handler: handlers/find.handler
    events:
      - http:
          path: /users
          method: get
          cors: true
