service: database-finance-service

frameworkVersion: "2"

plugins:
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      noStart: true
      seed: true
      port: 4566
    seed:
      finance:
        sources:
          - table: ${self:provider.stage}-DB-FS-Users
            sources: [ '../seed/users.json' ] 

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

resources:
  Resources:
    Users: ${file(tables/users.yml):Users}
    Accounts: ${file(tables/accounts.yml):Accounts}
  
  Outputs:
    AccountsArn:
      Value:
        Fn::GetAtt: 
          - Accounts
          - Arn
      Export:
        Name: ${self:provider.stage}-DB-FS-AccountsArn