Users:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.stage}-DB-FS-Users
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH